services:
  epenal-backend:
    image: 'epenal-backend:v.0.1'
    container_name: epenal-backend
    depends_on:
      - epenaldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://epenaldb:5432/epenaldb
      - SPRING_DATASOURCE_USERNAME=epenal
      - SPRING_DATASOURCE_PASSWORD=epenal
    ports:
      - "8082:8080"

  epenaldb:
    image: 'postgres'
    container_name: epenaldb
    environment:
      - POSTGRES_USER=epenal
      - POSTGRES_PASSWORD=epenal
      - PGDATA=/data/postgres
      - POSTGRES_DB=epenaldb
    volumes:
      - epenaldb:/data/postgres
volumes:
  epenaldb: